eval transforms error fixed
-eval method isn't working with single input in transforms.Resize() due to tensors mismatch
RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 0. Got 168 and 149 in dimension 3 at /opt/conda/conda-bld/pytorch_1573049306803/work/aten/src/TH/generic/THTensor.cpp:689